### ISSUE TITLE
Issues (0.8 user)

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#112]
Hi

First of all thank you for your great contents, and quick updates about some of the bugs.

Still some reports and questions coming here : 

1 - The character selection page seems broken, and everything excepting TAGS has disapeared. No favorite nor folder browser.
![Screenshot_16](https://user-images.githubusercontent.com/76269190/110024207-6320e580-7d2e-11eb-8dfd-c945bdd0e9f1.png)

2 - I have hundreds of characters with textures set to a specific status and/or unchecked to a specific customization. (from version HD Pro_win64_0.8.1.107)
 Is it possible to have version where these can be as protected as possible ? right now almost feels like it's wiped and reseted. I could do it all again once again but really need a version to stabilize that at some point...

3 - Some of the Morphs aren't working anymore on some characters, like clothes OFF etc.

4 - I am always using the same customization of "outfit Shape" for pantyhoses, but it's kind of a waste of time to adjust the same thing on every characters. Is there any way I can overwrite the default "Preset 1" to something I use most ?

5 -The new "quick menu" and other changes of key settings etc feels very unconvinient to me. For example, clicking on a character and "replacing" it doesn't replace that one, but another in the list that the software choose. I like to have mulple characters in scene and this is very annoying. It was better when we clicked on a character and opened it's settings with replace button to aim that one to change. Also, we can't easily close all menus with the A button(oculus) anymore and it make me click on characters by error.

6 - Some "transparent" textures aren't working. Even if they are in Transparent shader, they look opaque. It's scary when it comes to eye highlight, it's just black eyes.

**If I may ask, the latest working version without too much problem for me was 0.8.1.107, although "load last scene" didn't work and loading scenes only loaded half of the characters (very annoying). I know you had put lot of efforts into developping new features but lots of bugs have appeared and my humble feedback is that many of the new features/changes aren't making it better. The only amazing change is the Motion enhancement with the center checkbox. I would just love to have a 0.8.1 version with that implemented. Or maybe your updates should come as a choice in the settings (like checkboxes to use new features..)**

By the way the recent update about body centering really improves some motions ! Thanks !!

Keep up the good work please !

**Comment by alloystorm** [comment]
1. Does this happen all the time or just occasionally? Would refresh content help? 
2. Sorry for the trouble and thanks for the understanding. The texture settings changes should be settled down now, I'm not expecting any breaking changes in that area in the future and we will be extra careful when making future changes that could affect existing save files. 
3. Morph issue, it would be really helpful if you can send us an example. 
4. You can save your preset, however it's a bit broken in 0.9, will fix in the next hotfix release.
5. The "back" button should be able to dismiss all visible quick menus. By default this is assigned to left controller button 1, or "Tab" key on keyboard. You can change this in settings. Previously this was using the "Grip" button but it conflicts with drag drop motion all the time so it's been moved to button 1 by default. 
6. If the texture is within a group, you'll need to either change its mode in the sub item in the group or if you want to change the entire group you need to tick the "Override" box. The UI might be a bit confusing.

**Comment by alloystorm** [comment]
About the "Outfit" presets, I realized what you mean. At the moment presets for one actor cannot be carried over to another, this is a limitation of the currently implementation and I don't have a quick fix for that I'm sorry. Will see what can be next in the next release though...

**Comment by hboxgames** [comment]
Hi !

Thank you for your quick feedbacks !

Here are the answers and some more thoughts :
1 - It does happen mostly and the refresh doesn't help. When I restart it's even worse sometime, the stage and motion list is completely empty and the only way to fix it half is to replace a backup of the "cache" file. I even tried to erase it to see if the new version would create a new one, but what I realize is that it doesn't update or create anything. For example I added new files in the content folder and refreshed but they never appeared. Also, when I only have "Tags" on the windows, it doesn't mean I can see all the models. some just aren't in the tags anymore as well.

2 - That is a great news already, maybe I would start rebuilding everything once then haha.

3 - https://we.tl/t-Jg9hFCXBLU  Here is an example of model that reads, but some morphs don't react

4 - Yes, that is what I meant thanks ! Well, I don't know how complex it is for you but if we can't have outfits imported from one to another, some button that allows to save something as a new "default" would just be a great thing.

5 - I see thanks ! It did work to replace it to the BACK button, but one thing a bit bugging this time ... is that once all menu is off, the trigger grabs the scene like an objects and rotate it.

6 - well I did change manually to transparent shader and it remained opaque. I may try back and forth with the override option maybe it would work somehow ...
------
**7 - sorry to add up issues but found out some other major thing for me.. The eye contact option changed, in a way "EYE LIMIT" disapeared. Now it's pretty buggy and scary for mmd/unrealistic models. And since the eyes doesn't follow the tilt the head. Its is possible to put it back ?**

8 - most camera modes are buggy for me, it is not following the path or a character, it's kinda randomly.

9 - And the replace button randomly changes characters, not the one we chose. I think it was very useful to have the button it on the setting screen. By the way, the name shown on a character's setting screen is not always matching with the one we choose.

Thanks again and good luck ! Looking forward for updates, and I'll play a bit around to see if there's something else.

**Comment by alloystorm** [comment]
1 It sounds like the content scan issue that we've addressed, can you try the latest build and see if that helps? 
7 You can tick the "Cartoon" box to limit the eye movement for models with big eyes.
9 This has been fixed in the latest build

**Comment by hboxgames** [comment]
Hi !
1 -Yeah I in v141 and it was still happening the same ...

7 - Oh thanks my bad, didn't notice !

9 - Great ! thanks !

**Comment by alloystorm** [comment]
Are you able to send us your log file so we can investigate further? 

There should be 2 log files "Player.log" & "Player-prev.log" located in your system drive under C:\Users\[YOUR_USER_NAME]\AppData\LocalLow\VR Storm Lab\DanceViewerVR HD\, just replace [YOUR_USER_NAME] with your actual username on the system.

If you manage to reproduce that problem and then send the log file to us, we might be able to see what error is causing that problem.

**Comment by hboxgames** [comment]
Hi !
I just opened and was in the state where I have nothing in the motion/stage and only tags for actors.
[DanceViewerVR HD.zip](https://github.com/alloystorm/dvvr/files/6102221/DanceViewerVR.HD.zip)
Here are the files ! thanks !

**Comment by hboxgames** [comment]
Hey !
Just came to let you know that I found a mysterious fix to this. What I simply did, is to open the v8 once to create an updated cache file and open the v.9 again. Then all the menu/updating problem disapeared ... Well I guess we can keep this for other people who would have the same issue !

By the way, if it's not a big trouble, I was thinking about the auto-cam : If we have an option to switch characters by X beat it could be fun(right now it jumps around the selected character). Just an idea of future feature !

Keep up the great work !!

**Comment by alloystorm** [comment]
There are 2 errors I can see from the logs. 

One is related to _NEW_011120\_IMAS\アイマスOFAドリーミンイリース ver.1.1.zip, it may have trouble with the Japanese characters of the filenames within the zip. 
The other one is with sorting the saved scenes. 

Before we get those issues fixed, can you try remove the aforementioned zip file and clear your saved scenes and see if that solves the issue?

**Comment by hboxgames** [comment]
Hey !
As I said up there, I am not even sure why it fixed but it did.. but that is a good mention, maybe those characters were somehow bugging the former cache file I had? I don't know haha

**Comment by alloystorm** [comment]
Release build 145 to address the 2 errors seen from your logs.
