### ISSUE TITLE
Previously working Motions still not working well on new

### ISSUE THREAD

**Issue by hboxgames** [alloystorm/dvvr#158]
Hi !

Thanks for the great updates as always. Can't wait to see some fixes done this month if any ...

So, meanwhile I was trying to test out these motions since you were kinda saying it was fixed, if it isn't a misunderstanding.
The **black mamba** one is something I mentionned before : 
-It was perfectly working in old versions, IF WE UNCHECK the center offset.
-Now, it's broken when it's unchecked, and kinda little bit better when we **Check the center offset + put it to minimum(-20)**
-So, I don't know what happened in terms of programming, but my suggestion would be to get rid of the limit for offset ? like until -50 or something ..

Second motion is something I never sent you, different creator, recently got it. But it just look bad I guess, the video shows that it could look better : https://www.youtube.com/watch?v=nGiu-dEyads

Here are the files, Thanks in advance and keep on the great work !!
https://we.tl/t-V8uXMnqcvX

 (please don't change too much the pipeline of the materials and stuff it's working great now and I'm re-setting all my models T.T)

**Comment by alloystorm** [comment]
Thank you for the files. Will look into them.

**Comment by alloystorm** [comment]
Fixed in 1.1.3

**Comment by hboxgames** [comment]
Ah I understand ! I felt like it's smoother on feet contact but it's still user made anyway !
Thanks , can't wait for the update !

**Comment by hboxgames** [comment]
Hi ! 
Tried out 113 version just now.. pretty shocked with all the models reset again ..
By the way, the centeroffset wasn't solved with the motions series I sent you (the other one, not baddest)
If you play them with oold versions, you will notice their foot placement are perfect. Or is it because I didn't find how to solve it in the new version ?

**Comment by alloystorm** [comment]
For the model I test it with, the best value for center offset is 0.36. Depends on the model, you might need a lightly different value. 

If you move the timeline to 00:47, the actor will appear above ground, you can then adjust the center offset value until the actor's feet touch ground. That should be the best value for the model.

**Comment by alloystorm** [comment]
Let me know if you still couldn't get it to work.

**Comment by hboxgames** [comment]
Oh ok it works ! 
So we control it basically only in the motion setting. And that method with height is great to find out the good setting thanks !
