### ISSUE TITLE
Motions not loading

### ISSUE THREAD

**Issue by chengsta** [alloystorm/dvvr#45]
Hello, these motions I have linked in the google drive do not load. https://drive.google.com/open?id=1cwrtfLvzZVYj6X21wklhhBppBb5UA32P
 The character just goes into a 'T' pose.  sometimes the music will play but nothing else.  They all work fine in MMD.  Please help when you have time, thanks!

**Comment by Terell2018** [comment]
It the motion is not loading there a problem with DVVR 0.5.3. and there is a DVVR 0.5.3a which is fixed the motion that are not loading. that is a public version.

**Comment by chengsta** [comment]
ok cool, i didn't realize the public version got it fixed.  I tried it, but 'birthday' and 'kpopstars' still isn't loading, just a T pose.  But at least the other half load now, thanks.

**Comment by Terell2018** [comment]
The motion call MAMAMOO - Egotistic [Mirin] from mikumikudance the motion have 1 minute and 12 second. and the wav have 3 minute and 34 second wit it mean the wav since long than the motion wit is still playing.
