### ISSUE TITLE
Doesn't recognize motion folder correctly

### ISSUE THREAD

**Issue by Jarius86** [alloystorm/dvvr#65]
(0.6.2 public)

The motion folder isn't being recognized properly. The actors and stages folders are just fine, but it only sees one file in the motion folder, a .wav that it seems to have mistaken for a motion. There are probably thousands of .vmd and .vpd files in there, if it's important.

I initially tried making symbolic links to the folders, because I already have around 60GB of files for WSS that I didn't want to have to duplicate, and that works fine for the actors and stages folders, but neither symbolic links nor just copying everything over works for the motion folder.

This is my motion folder:
![dvvr bug 3](https://user-images.githubusercontent.com/43699598/83460064-cd64cc80-a422-11ea-8354-e414a2004b92.png)

And this is what dvvr sees:
![dvvr bug 1](https://user-images.githubusercontent.com/43699598/83460100-db1a5200-a422-11ea-8995-83bf1e957aa6.png)
![dvvr bug 2](https://user-images.githubusercontent.com/43699598/83460108-e1103300-a422-11ea-8d29-cdaca1ac8564.png)

**Comment by alloystorm** [comment]
Try force refresh the content library in settings -> options -> refresh content. Or delete the cache.json file in your content folder. The program won't scan the library if the cache exists.

**Comment by alloystorm** [comment]
Let me know if that doesn't help. I use a lot of content from WSS too, working fine for me.

**Comment by Jarius86** [comment]
I've tried both of those, it didn't help. Would it have something to do with the fact that I've added my own motions to the folder? I've put them in a folder called 00 User Motions so that they're first alphabetically

**Comment by alloystorm** [comment]
Could you run "tree > tree.txt" from your content folder, and attach the generated tree.txt file as well as the cache.json so we can see your folder structure? Thanks.

**Comment by alloystorm** [comment]
Fixed in 0.6.3c

**Comment by Jarius86** [comment]
Issue is still present in 0.6.3c. There's nothing called "tree" in the content folder. Sorry for the late reply.

**Comment by alloystorm** [comment]
Here's what I mean by running tree command. 

Press WIN + R key on your keyboard in Windows, type cmd and Enter to launch "Command Prompt" 
Then navigate to your content folder by typing "cd <path-to-the-folder>" and Enter, you can drag & drop from Explorer window on to the "Command Prompt" to automatically populate the full path of the folder.
Then type in "tree > tree.txt" and enter
After it is finished you should be able to see a "tree.txt" file in your content folder that shows the entire folder structure. 
You can attach the file here so we can research further. 

Are you sure running "refresh content" in version 0.6.3c is not working? We did have an issue with the content scan but it should be fixed in the latest release.
